\set ON_ERROR_STOP on

DROP TABLE IF EXISTS enrollment CASCADE;
DROP TABLE IF EXISTS completed_course CASCADE;
DROP TABLE IF EXISTS prerequisite CASCADE;
DROP TABLE IF EXISTS course_time CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS department CASCADE;

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP
);

CREATE TABLE member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT uk_member_email UNIQUE (email)
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    current_count INTEGER NOT NULL DEFAULT 0,
    version BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT chk_course_capacity_non_negative CHECK (capacity >= 0),
    CONSTRAINT chk_course_current_count_non_negative CHECK (current_count >= 0)
);

CREATE TABLE student (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    member_id BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT fk_student_department FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT fk_student_member FOREIGN KEY (member_id) REFERENCES member(member_id)
);

CREATE TABLE course_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    location VARCHAR(50),
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT fk_course_time_course FOREIGN KEY (course_id) REFERENCES course(id),
    CONSTRAINT chk_course_time_order CHECK (start_time < end_time)
);

CREATE TABLE prerequisite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    pre_course_id BIGINT,
    department_id BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT fk_prerequisite_course FOREIGN KEY (course_id) REFERENCES course(id),
    CONSTRAINT fk_prerequisite_pre_course FOREIGN KEY (pre_course_id) REFERENCES course(id),
    CONSTRAINT fk_prerequisite_department FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE completed_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT uk_student_completed_course UNIQUE (student_id, course_id),
    CONSTRAINT fk_completed_course_student FOREIGN KEY (student_id) REFERENCES student(student_id),
    CONSTRAINT fk_completed_course_course FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    CONSTRAINT uk_student_course UNIQUE (student_id, course_id),
    CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES student(student_id),
    CONSTRAINT fk_enrollment_course FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE INDEX idx_enrollment_student ON enrollment(student_id);
CREATE INDEX idx_enrollment_course ON enrollment(course_id);
CREATE INDEX idx_completed_course_student ON completed_course(student_id);
CREATE INDEX idx_completed_course_course ON completed_course(course_id);
CREATE INDEX idx_prerequisite_course ON prerequisite(course_id);
CREATE INDEX idx_prerequisite_covering ON prerequisite(course_id, department_id, pre_course_id);
CREATE INDEX idx_course_time_course ON course_time(course_id);
CREATE INDEX idx_student_department ON student(department_id);
